### PR TITLE
sunxi-pwm: Fix broken PWM_SUNXI_ENHANCE driver

### PR DESCRIPTION
**Pull request by chraac**
## Background

In PR https://github.com/armbian/build/pull/6617, we've added the ethernet and pwm driver for zero2w for kernel version 6.6 and 6.7, now in 6.10, the pwm drvier interface have been changed that makes our driver failed to compile, here's a PR to fix that.

## Changes:

- Fix compiling error at the patch drivers-pwm-Add-pwm-sunxi-enhance-driver-for-h616.patch, adapt to new 6.10 pwm interface
- Fix `driver-allwinner-h618-emac.patch`, now ethernet on zero2w works well
- At sunxi64 edge config, enable CONFIG_PWM_SUNXI_ENHANCE as module

## How Has This Been Tested?
- [x] Build and install to zero2w, the ethernet works well
    image

### CODE REVIEW

**Comment by chraac** [comment]
For the indentation issues, can have a commit to change the driver into tab ident

**Comment by The-going** [comment]
@chraac Good health!
Good job!

If you don't mind, can I clean up the history a bit?

**Comment by The-going** [comment]
> For the indentation issues, can have a commit to change the driver into tab ident

You don't have to worry. I'll do it myself.

**Comment by chraac** [comment]
> @chraac Good health! Good job!
> 
> If you don't mind, can I clean up the history a bit?

sure, gonna squash all the versions into one and clear the log.

**Comment by The-going** [comment]
@chraac Thank you very much.
I've taken all your changes and will add them after I fix mine, the ones that go before that.

**Comment by chraac** [comment]
> @chraac Thank you very much. I've taken all your changes and will add them after I fix mine, the ones that go before that.

Cool! Do you mind merge this PR into your branch? Now I've squash all changes into one commit.

**Comment by The-going** [comment]
> Now I've squash all changes into one commit.

@chraac PR is merged  in cmdline.

**Pull request closed without merging**
